---
- name: Copy Graylog configuration file from the custom template
  template:
    src: "{{ graylog_host_config_file_path }}"
    dest: "{{ graylog_config_file_path }}"
    owner: root
    group: root
    mode: 0644
  when: graylog_config_check.stat.exists
  notify: Restart Graylog

- name: Copy Graylog configuration file
  template:
    src: server.conf.j2
    dest: "{{ graylog_config_file_path }}"
    owner: root
    group: root
    mode: 0644
  when: not graylog_config_check.stat.exists
  notify: Restart Graylog

- name: Copy Graylog default configuration file (Ubuntu/Debian)
  template:
    src: graylog.default.j2
    dest: /etc/default/graylog-server
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'
  notify: Restart Graylog

- name: Copy Graylog default configuration file (CentOS/RHEL)
  template:
    src: graylog.default.j2
    dest: /etc/sysconfig/graylog-server
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'RedHat'
  notify: Restart Graylog