---
- name: Set fact variable for list each items
  set_fact:
    graylog_elasticsearch_facts: "{{ item }}"
  with_items: "{{ graylog_elasticsearch_hosts }}"
  register: graylog_elasticsearch_facts_output

- name: Set fact variable for all host Elasticsearch
  set_fact:
    graylog_elasticsearch_host_list: "{{ graylog_elasticsearch_facts_output.results | map(attribute='ansible_facts.graylog_elasticsearch_facts') | list }}"
  when: graylog_elasticsearch_facts_output.results is defined

- name: Copy Graylog configuration file
  template:
    src: "{{ graylog_host_config_file_path }}"
    dest: "{{ graylog_config_file_path }}"
    owner: root
    group: root
    mode: 0644
  when: graylog_config_check.stat.exists
  changed_when: yes
  notify: Restart Graylog

- name: Copy Graylog configuration file
  template:
    src: server.conf.j2
    dest: "{{ graylog_config_file_path }}"
    owner: root
    group: root
    mode: 0644
  notify: Restart Graylog

- name: Copy Graylog default configuration file (Ubuntu/Debian)
  template:
    src: graylog.default.j2
    dest: /etc/default/graylog-server
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'
  notify: Restart Graylog

- name: Copy Graylog default configuration file (CentOS/RHEL)
  template:
    src: graylog.default.j2
    dest: /etc/sysconfig/graylog-server
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'RedHat'
  notify: Restart Graylog