---
- include_tasks: graylog_pre.yml
- include_tasks: graylog_install.yml

- block: # Config Graylog
  - include_tasks: graylog_search_config.yml
  - include_tasks: graylog_post.yml
  tags:
    - graylog-config